# Generated by Django 5.2.1 on 2025-07-29 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0001_initial'),
    ]

    operations = [
    ]
